#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { minify } = require('terser');
const { minify: minifyHTML } = require('html-minifier-terser');
const cssnano = require('cssnano');
const postcss = require('postcss');

// Загружаем конфигурацию Terser
const terserConfig = require('./terser.config.js');

// Настройки
const COMPONENTS_DIR = './web-components';
const OUTPUT_SUFFIX = '.min';

// Конфигурация HTML минификации
const htmlMinifierConfig = {
  collapseBooleanAttributes: true,
  collapseInlineTagWhitespace: true,
  collapseWhitespace: true,
  conservativeCollapse: false,
  decodeEntities: true,
  html5: true,
  includeAutoGeneratedTags: false,
  keepClosingSlash: false,
  minifyCSS: false, // Мы минифицируем CSS отдельно
  minifyJS: false,  // Не минифицируем JS внутри HTML
  preserveLineBreaks: false,
  preventAttributesEscaping: false,
  processConditionalComments: false,
  removeAttributeQuotes: false, // Оставляем кавычки для совместимости
  removeComments: true,
  removeEmptyAttributes: true,
  removeEmptyElements: false, // Не удаляем пустые элементы (могут быть нужны)
  removeOptionalTags: false,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  removeTagWhitespace: false,
  sortAttributes: false,
  sortClassName: false,
  trimCustomFragments: true,
  useShortDoctype: true
};

// Конфигурация CSS минификации
const cssMinifierConfig = {
  preset: ['default', {
    discardComments: { removeAll: true },
    discardDuplicates: true,
    discardEmpty: true,
    discardOverridden: true,
    discardUnused: false, // Не удаляем CSS, так как он может использоваться динамически
    mergeLonghand: true,
    mergeRules: true,
    minifyFontValues: true,
    minifyGradients: true,
    minifySelectors: true,
    normalizeCharset: true,
    normalizeDisplayValues: true,
    normalizePositions: true,
    normalizeRepeatStyle: true,
    normalizeString: true,
    normalizeTimingFunctions: true,
    normalizeUnicode: true,
    normalizeUrl: true,
    normalizeWhitespace: true,
    reduceIdents: false, // Не изменяем CSS идентификаторы для безопасности
    reduceInitial: true,
    reduceTransforms: true,
    uniqueSelectors: true,
    zindex: false // Не оптимизируем z-index
  }]
};

// Утилита для форматирования размеров файлов
function formatBytes(bytes, decimals = 2) {
  if (bytes === 0) return '0 Bytes';
  const k = 1024;
  const dm = decimals < 0 ? 0 : decimals;
  const sizes = ['Bytes', 'KB', 'MB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
}

// Утилита для вычисления степени сжатия
function getCompressionRatio(originalSize, minifiedSize) {
  const ratio = ((originalSize - minifiedSize) / originalSize) * 100;
  return Math.round(ratio * 100) / 100;
}

// Минификация CSS строки
async function minifyCSSString(cssString) {
  try {
    const result = await postcss([cssnano(cssMinifierConfig)])
      .process(cssString, { from: undefined });
    return result.css;
  } catch (error) {
    console.warn('⚠️  CSS минификация не удалась, используем оригинал:', error.message);
    return cssString;
  }
}

// Минификация HTML строки
async function minifyHTMLString(htmlString) {
  try {
    return await minifyHTML(htmlString, htmlMinifierConfig);
  } catch (error) {
    console.warn('⚠️  HTML минификация не удалась, используем оригинал:', error.message);
    return htmlString;
  }
}

// Обработка JavaScript кода для минификации встроенных CSS и HTML
async function preprocessJavaScript(code) {
  let processedCode = code;
  let cssMinificationSavings = 0;
  let htmlMinificationSavings = 0;

  // Регулярное выражение для поиска getStyles() метода
  const getStylesRegex = /getStyles\(\)\s*{\s*return\s*`([^`]+)`\s*;?\s*}/gs;
  const getStylesMatches = [...code.matchAll(getStylesRegex)];

  for (const match of getStylesMatches) {
    const originalCSS = match[1];
    const originalSize = Buffer.byteLength(originalCSS, 'utf8');
    
    // Минифицируем CSS
    const minifiedCSS = await minifyCSSString(originalCSS);
    const minifiedSize = Buffer.byteLength(minifiedCSS, 'utf8');
    
    cssMinificationSavings += originalSize - minifiedSize;
    
    // Заменяем в коде
    const newMethod = match[0].replace(originalCSS, minifiedCSS);
    processedCode = processedCode.replace(match[0], newMethod);
  }

  // Регулярное выражение для поиска getTemplate() метода
  const getTemplateRegex = /getTemplate\(\)\s*{\s*return\s*`([^`]+)`\s*;?\s*}/gs;
  const getTemplateMatches = [...code.matchAll(getTemplateRegex)];

  for (const match of getTemplateMatches) {
    const originalHTML = match[1];
    const originalSize = Buffer.byteLength(originalHTML, 'utf8');
    
    // Минифицируем HTML
    const minifiedHTML = await minifyHTMLString(originalHTML);
    const minifiedSize = Buffer.byteLength(minifiedHTML, 'utf8');
    
    htmlMinificationSavings += originalSize - minifiedSize;
    
    // Заменяем в коде
    const newMethod = match[0].replace(originalHTML, minifiedHTML);
    processedCode = processedCode.replace(match[0], newMethod);
  }

  return {
    code: processedCode,
    cssMinificationSavings,
    htmlMinificationSavings
  };
}

// Получение списка всех .js файлов в папке веб-компонентов
function getComponentFiles() {
  if (!fs.existsSync(COMPONENTS_DIR)) {
    console.error(`❌ Папка ${COMPONENTS_DIR} не найдена!`);
    process.exit(1);
  }

  const files = fs.readdirSync(COMPONENTS_DIR)
    .filter(file => file.endsWith('.js') && !file.endsWith('.min.js'))
    .map(file => path.join(COMPONENTS_DIR, file));

  if (files.length === 0) {
    console.error(`❌ В папке ${COMPONENTS_DIR} не найдено .js файлов!`);
    process.exit(1);
  }

  return files;
}

// Минификация одного файла
async function minifyFile(inputPath) {
  try {
    console.log(`🔄 Минификация: ${path.basename(inputPath)}`);
    
    // Читаем исходный файл
    const originalCode = fs.readFileSync(inputPath, 'utf8');
    const originalSize = Buffer.byteLength(originalCode, 'utf8');
    
    // Шаг 1: Предварительная обработка CSS и HTML
    console.log(`   📝 Минификация CSS и HTML...`);
    const preprocessed = await preprocessJavaScript(originalCode);
    const preprocessedSize = Buffer.byteLength(preprocessed.code, 'utf8');
    
    // Шаг 2: Минификация JavaScript с помощью Terser
    console.log(`   🗜️  Минификация JavaScript...`);
    const result = await minify(preprocessed.code, terserConfig);
    
    if (result.error) {
      throw new Error(result.error);
    }
    
    const minifiedCode = result.code;
    const minifiedSize = Buffer.byteLength(minifiedCode, 'utf8');
    
    // Создаем путь к минифицированному файлу
    const ext = path.extname(inputPath);
    const baseName = path.basename(inputPath, ext);
    const outputPath = path.join(
      path.dirname(inputPath), 
      `${baseName}${OUTPUT_SUFFIX}${ext}`
    );
    
    // Записываем минифицированный файл
    fs.writeFileSync(outputPath, minifiedCode, 'utf8');
    
    // Вычисляем статистику
    const compressionRatio = getCompressionRatio(originalSize, minifiedSize);
    const preprocessSavings = originalSize - preprocessedSize;
    const terserSavings = preprocessedSize - minifiedSize;
    
    const stats = {
      inputPath,
      outputPath,
      originalSize,
      minifiedSize,
      compressionRatio,
      cssMinificationSavings: preprocessed.cssMinificationSavings,
      htmlMinificationSavings: preprocessed.htmlMinificationSavings,
      preprocessSavings,
      terserSavings,
      success: true
    };
    
    console.log(`✅ ${path.basename(inputPath)}: ${formatBytes(originalSize)} → ${formatBytes(minifiedSize)} (${compressionRatio}% сжатие)`);
    if (preprocessed.cssMinificationSavings > 0) {
      console.log(`   🎨 CSS: ${formatBytes(preprocessed.cssMinificationSavings)} экономии`);
    }
    if (preprocessed.htmlMinificationSavings > 0) {
      console.log(`   📄 HTML: ${formatBytes(preprocessed.htmlMinificationSavings)} экономии`);
    }
    
    return stats;
    
  } catch (error) {
    console.error(`❌ Ошибка при минификации ${path.basename(inputPath)}:`, error.message);
    return {
      inputPath,
      outputPath: null,
      originalSize: 0,
      minifiedSize: 0,
      compressionRatio: 0,
      success: false,
      error: error.message
    };
  }
}

// Основная функция минификации всех компонентов
async function minifyAllComponents() {
  console.log('🚀 Начинаем минификацию веб-компонентов...\n');
  
  const componentFiles = getComponentFiles();
  const results = [];
  
  // Минифицируем каждый файл
  for (const file of componentFiles) {
    const result = await minifyFile(file);
    results.push(result);
  }
  
  // Генерируем отчет
  generateReport(results);
}

// Генерация отчета
function generateReport(results) {
  console.log('\n📊 ОТЧЕТ О МИНИФИКАЦИИ');
  console.log('='.repeat(80));
  
  const successful = results.filter(r => r.success);
  const failed = results.filter(r => !r.success);
  
  if (successful.length > 0) {
    console.log(`\n✅ Успешно минифицировано: ${successful.length} файлов\n`);
    
    let totalOriginalSize = 0;
    let totalMinifiedSize = 0;
    let totalCSSMinificationSavings = 0;
    let totalHTMLMinificationSavings = 0;
    
    successful.forEach(result => {
      const fileName = path.basename(result.inputPath);
      const minFileName = path.basename(result.outputPath);
      
      console.log(`   ${fileName}`);
      console.log(`   → ${minFileName}`);
      console.log(`   📏 ${formatBytes(result.originalSize)} → ${formatBytes(result.minifiedSize)} (${result.compressionRatio}% сжатие)`);
      
      if (result.cssMinificationSavings > 0) {
        console.log(`   🎨 CSS: ${formatBytes(result.cssMinificationSavings)} экономии`);
      }
      if (result.htmlMinificationSavings > 0) {
        console.log(`   📄 HTML: ${formatBytes(result.htmlMinificationSavings)} экономии`);
      }
      console.log('');
      
      totalOriginalSize += result.originalSize;
      totalMinifiedSize += result.minifiedSize;
      totalCSSMinificationSavings += result.cssMinificationSavings || 0;
      totalHTMLMinificationSavings += result.htmlMinificationSavings || 0;
    });
    
    const totalCompressionRatio = getCompressionRatio(totalOriginalSize, totalMinifiedSize);
    
    console.log('📈 ОБЩАЯ СТАТИСТИКА:');
    console.log(`   Исходный размер:      ${formatBytes(totalOriginalSize)}`);
    console.log(`   Минифицированный:     ${formatBytes(totalMinifiedSize)}`);
    console.log(`   Общее сжатие:         ${totalCompressionRatio}%`);
    console.log(`   Экономия:             ${formatBytes(totalOriginalSize - totalMinifiedSize)}`);
    
    if (totalCSSMinificationSavings > 0 || totalHTMLMinificationSavings > 0) {
      console.log('\n🎯 ДЕТАЛИЗАЦИЯ ПО ТИПАМ:');
      if (totalCSSMinificationSavings > 0) {
        console.log(`   🎨 CSS минификация:   ${formatBytes(totalCSSMinificationSavings)} экономии`);
      }
      if (totalHTMLMinificationSavings > 0) {
        console.log(`   📄 HTML минификация:  ${formatBytes(totalHTMLMinificationSavings)} экономии`);
      }
      const jsMinificationSavings = (totalOriginalSize - totalMinifiedSize) - totalCSSMinificationSavings - totalHTMLMinificationSavings;
      console.log(`   🗜️  JS минификация:    ${formatBytes(jsMinificationSavings)} экономии`);
    }
  }
  
  if (failed.length > 0) {
    console.log(`\n❌ Не удалось минифицировать: ${failed.length} файлов\n`);
    failed.forEach(result => {
      console.log(`   ${path.basename(result.inputPath)}: ${result.error}`);
    });
  }
  
  console.log('\n🏁 Минификация завершена!');
  
  // Сохраняем подробный отчет в JSON
  const reportPath = './minification-report.json';
  const totalOriginalSize = successful.reduce((sum, r) => sum + r.originalSize, 0);
  const totalMinifiedSize = successful.reduce((sum, r) => sum + r.minifiedSize, 0);
  const totalCSSMinificationSavings = successful.reduce((sum, r) => sum + (r.cssMinificationSavings || 0), 0);
  const totalHTMLMinificationSavings = successful.reduce((sum, r) => sum + (r.htmlMinificationSavings || 0), 0);
  
  fs.writeFileSync(reportPath, JSON.stringify({
    timestamp: new Date().toISOString(),
    results,
    summary: {
      total: results.length,
      successful: successful.length,
      failed: failed.length,
      totalOriginalSize,
      totalMinifiedSize,
      totalCompressionRatio: getCompressionRatio(totalOriginalSize, totalMinifiedSize),
      totalCSSMinificationSavings,
      totalHTMLMinificationSavings,
      totalJSMinificationSavings: (totalOriginalSize - totalMinifiedSize) - totalCSSMinificationSavings - totalHTMLMinificationSavings
    }
  }, null, 2));
  
  console.log(`📄 Подробный отчет сохранен: ${reportPath}`);
}

// Функция для минификации одного конкретного файла (для тестирования)
async function minifySingleFile(fileName) {
  const filePath = path.join(COMPONENTS_DIR, fileName);
  
  if (!fs.existsSync(filePath)) {
    console.error(`❌ Файл ${filePath} не найден!`);
    process.exit(1);
  }
  
  console.log(`🧪 Тестовая минификация файла: ${fileName}\n`);
  
  const result = await minifyFile(filePath);
  generateReport([result]);
}

// Обработка аргументов командной строки
const args = process.argv.slice(2);

if (args.length > 0) {
  // Минификация конкретного файла
  const fileName = args[0];
  minifySingleFile(fileName);
} else {
  // Минификация всех файлов
  minifyAllComponents();
}

// Обработка ошибок
process.on('uncaughtException', (error) => {
  console.error('❌ Критическая ошибка:', error.message);
  process.exit(1);
});

process.on('unhandledRejection', (reason, promise) => {
  console.error('❌ Необработанная ошибка Promise:', reason);
  process.exit(1);
});